# Generated by Django 4.0 on 2025-02-09 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advance', models.IntegerField()),
                ('Payment_Method', models.CharField(choices=[('Bank', 'Bank'), ('Esewa', 'Esewa'), ('Khalti', 'Khalti'), ('Cash', 'Cash'), ('PhonePay', 'PhonePay')], default='Cash', max_length=50)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.customer')),
            ],
        ),
    ]
